# Generated by Django 4.2.1 on 2023-05-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="total",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
