# Generated by Django 4.2.1 on 2023-06-03 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_username"),
        ("report", "0002_cost_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="member_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.profile",
                to_field="member_number",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
