# Generated by Django 4.2.1 on 2023-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_test1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_item", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Debit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit_item", models.CharField(max_length=100)),
            ],
        ),
    ]
