# Generated by Django 4.2.1 on 2023-06-19 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_profile_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0007_credit_debit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exec_day", models.DateField(help_text="仕分実行日")),
                ("debit_amount", models.IntegerField()),
                ("credit_amount", models.IntegerField()),
                ("comment", models.TextField()),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.credit"
                    ),
                ),
                (
                    "debit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.debit"
                    ),
                ),
                (
                    "exec_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exec_user_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.profile",
                        to_field="member_number",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
            ],
        ),
    ]
