# Generated by Django 4.2.1 on 2023-05-28 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_number",
                    models.IntegerField(
                        default=0,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("telephone_number", models.BigIntegerField()),
                ("email", models.CharField(default="", max_length=40)),
                ("zipcode", models.CharField(default="", max_length=8)),
                ("prefecture", models.CharField(default="", max_length=6)),
                ("city", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
